[tool.poetry]
name = "themore-amazon"
version = "0.2.0"
description = ""
readme = "README.md"
authors = ["cda2 <qq23667@gmail.com>"]

[tool.autoflake]
remove-all-unused-imports = true
in-place = true

[tool.black]
line-length = 80

[tool.isort]
line_length = 80
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.poetry.dependencies]
python = "^3.10"
playwright = "^1.35.0"
pyyaml = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
