[tool.poetry]
name = "themore-amazon"
version = "0.2.0"
description = ""
readme = "README.md"
authors = ["cda2 <qq23667@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
playwright = "^1.35.0"
pyyaml = "^6.0"
amazoncaptcha = "^0.5.11"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.287"
black = "^23.7.0"

[tool.black]
line-length = 80

[tool.ruff]
line-length = 80
fix = true
select = [
    "E", # pycodestyle errors
    "F", # pyflakes
    "I", # isort
    "C", # flake8-comprehensions
    "A", # flake8-builtins
    "COM", # flake8-commas
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
    "PT", # flake8-pytest-style
    "ASYNC", # flake8-async
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
