[tool.poetry]
name = "themore-amazon"
version = "0.1.0"
description = ""
readme = "README.md"
packages = [{include = "themore_amazon"}]

[tool.poetry.dependencies]
python = "^3.10"
playwright = "^1.35.0"
pyyaml = "^6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
